((nil (indent-tabs-mode . t))
 (cmake-mode . ((indent-tabs-mode . nil)
				(buffer-file-coding-system . utf-8-with-signature-dos)))
 (markdown-mode . ((indent-tabs-mode . nil)
				   (buffer-file-coding-system . utf-8-with-signature-dos)))
 (c-mode . ((indent-tabs-mode . t)
			(buffer-file-coding-system . cp932-dos)))
 (c++-mode . ((indent-tabs-mode . t)
			(buffer-file-coding-system . cp932-dos)))
 (html-mode . ((indent-tabs-mode . nil)
			   (buffer-file-coding-system . cp932-dos)))
 )
