//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ttpdlg.rc
//
#define IDD_TERMDLGJ                    100
#define IDI_TTERM                       100
#define IDC_TERMWIDTH                   101
#define IDC_SERIALPORT_LABEL            101
#define IDC_TERMHEIGHT                  102
#define IDC_SERIALBAUD_LEBAL            102
#define IDC_TERMISWIN                   103
#define IDC_SERIALDATA_LABEL            103
#define IDC_TERMRESIZE                  104
#define IDC_SERIALPARITY_LABEL          104
#define IDC_TERMCRRCV                   105
#define IDC_SERIALSTOP_LABEL            105
#define IDC_TERMCRSEND                  106
#define IDC_SERIALFLOW_LABEL            106
#define IDC_TERMID                      107
#define IDC_TERMLOCALECHO               108
#define IDC_TERMANSBACKTEXT             109
#define IDC_TERMANSBACK                 110
#define IDC_TERMAUTOSWITCH              111
#define IDC_TERMKANJI                   112
#define IDC_TERMKANA                    113
#define IDC_TERMKANJISEND               114
#define IDC_TERMKANASEND                115
#define IDC_TERMKINTEXT                 116
#define IDC_TERMKIN                     117
#define IDC_TERMKOUTTEXT                118
#define IDC_TERMKOUT                    119
#define IDC_TERMRUSSHOST                120
#define IDC_TERMRUSSCLIENT              121
#define IDC_TERMHELP                    199
#define IDD_WINDLG                      200
#define IDC_WINTITLE                    201
#define IDC_WINBLOCK                    202
#define IDC_WINVERT                     203
#define IDC_WINHORZ                     204
#define IDC_WINHIDEMENU                 205
#define IDC_WINHIDETITLE                206
#define IDC_WINCOLOREMU                 207
#define IDC_WINSCROLL1                  208
#define IDC_WINSCROLL2                  209
#define IDC_WINSCROLL3                  210
#define IDC_WINTEXT                     211
#define IDC_WINBACK                     212
#define IDC_WINREV                      213
#define IDC_WINRED                      214
#define IDC_WINGREEN                    215
#define IDC_WINBLUE                     216
#define IDC_WINREDBAR                   217
#define IDC_WINGREENBAR                 218
#define IDC_WINBLUEBAR                  219
#define IDC_WINATTRTEXT                 220
#define IDC_WINATTR                     221
#define IDC_WINAIXTERM16                222
#define IDC_WINXTERM256                 223
#define IDC_WINUSENORMALBG              231
#define IDC_WINHELP                     299
#define IDD_KEYBDLG                     300
#define IDC_KEYBBS                      301
#define IDC_KEYBDEL                     302
#define IDC_KEYBMETA                    303
#define IDC_KEYBKEYBTEXT                304
#define IDC_KEYBKEYB                    305
#define IDC_KEYBDISABLE                 310
#define IDC_KEYBAPPKEY                  311
#define IDC_KEYBAPPCUR                  312
#define IDC_KEYBHELP                    399
#define IDD_SERIALDLG                   400
#define IDC_SERIALPORT                  401
#define IDC_SERIALBAUD                  402
#define IDC_SERIALDATA                  403
#define IDC_SERIALPARITY                404
#define IDC_SERIALSTOP                  405
#define IDC_SERIALFLOW                  406
#define IDC_SERIALDELAYCHAR             407
#define IDC_SERIALDELAYLINE             408
#define IDC_SERIALHELP                  499
#define IDD_TCPIPDLG                    500
#define IDC_TCPIPHOST                   501
#define IDC_TCPIPADD                    502
#define IDC_TCPIPLIST                   503
#define IDC_TCPIPUP                     504
#define IDC_TCPIPREMOVE                 505
#define IDC_TCPIPDOWN                   506
#define IDC_TCPIPHISTORY                507
#define IDC_TCPIPAUTOCLOSE              508
#define IDC_TCPIPPORT                   509
#define IDC_TCPIPTELNET                 510
#define IDC_TCPIPTERMTYPELABEL          511
#define IDC_TCPIPTERMTYPE               512
#define IDC_TCPIPTELNETKEEPALIVE        513
#define IDC_TCPIPTELNETKEEPALIVESEC     514
#define IDC_TCPIPHELP                   599
#define IDD_HOSTDLG                     600
#define IDC_HOSTTCPIP                   601
#define IDC_HOSTSERIAL                  602
#define IDC_HOSTNAMELABEL               603
#define IDC_HOSTNAME                    604
#define IDC_HOSTTELNET                  605
#define IDC_HOSTTCPPORTLABEL            606
#define IDC_HOSTTCPPORT                 607
#define IDC_HOSTCOMLABEL                608
#define IDC_HOSTCOM                     609
#define IDC_HOSTHELP                    699
#define IDD_DIRDLG                      700
#define IDC_DIRCURRENT                  701
#define IDC_DIRNEW                      702
#define IDC_DIRHELP                     799
#define IDD_ABOUTDLG                    800
#define IDD_FONTDLG                     900
#define IDC_FONTBOLD                    901
#define IDC_FONTCHARSET1                902
#define IDC_FONTCHARSET2                903
#define IDD_GENDLG                      1000
#define IDC_GENPORT                     1001
#define IDC_GENLANGLABEL                1002
#define IDC_GENLANG                     1003
#define IDC_GENPORT_LABEL               1004
#define IDC_HOSTTCPPROTOCOLLABEL        1019
#define IDC_HOSTTCPPROTOCOL             1020
#define IDC_LOCALE_BOX                  1022
#define IDC_EDIT1                       1024
#define IDC_LOCALE_EDIT                 1024
#define IDC_CODEPAGE_LABEL              1025
#define IDC_EDIT2                       1026
#define IDC_CODEPAGE_EDIT               1026
#define IDC_TT_VERSION                  1027
#define IDC_AUTHOR_URL                  1028
#define IDC_FORUM_LABEL                 1029
#define IDC_FORUM_URL                   1030
#define IDC_ONIGURUMA_LABEL             1031
#define IDC_RIGHTS_LABEL                1032
#define IDC_PROJECT_LABEL               1033
#define IDC_TERANISHI_LABEL             1034
#define IDC_TT_PRO                      1035
#define IDC_INLUCDE_LABEL               1036
#define IDC_TT23_LABEL                  1037
#define IDC_TT23DATE_LABEL              1038
#define IDC_FONTHELP                    1038
#define IDC_AUTHOR_LABEL                1039
#define IDC_TT_ICON                     1040
#define IDC_DIRCURRENT_LABEL            1041
#define IDC_DIRNEW_LABEL                1042
#define IDC_KEYBTRANS                   1043
#define IDC_SERIALDELAYLINE_LABEL       1044
#define IDC_SERIALDELAYCHAR_LABEL       1045
#define IDC_SERIALDELAY                 1046
#define IDC_TCPIPPROT                   1047
#define IDC_TCPIPPORTLABEL              1048
#define IDC_TCPIPHOSTLIST               1049
#define IDC_WINTITLELABEL               1050
#define IDC_WINCURSOR                   1051
#define IDC_WINREDLABEL                 1052
#define IDC_WINGREENLABEL               1053
#define IDC_WINBLUELABEL                1054
#define IDC_WINCOLOR                    1055
#define IDC_TERMWIDTHLABEL              1056
#define IDC_TERMX                       1057
#define IDC_TERMNEWLINE                 1058
#define IDC_TERMCRRCVLABEL              1059
#define IDC_TERMCRSENDLABEL             1060
#define IDC_TERMIDLABEL                 1061
#define IDC_TERMKANJILABEL              1062
#define IDC_TERMKANJISENDLABEL          1063
#define IDC_LOCALE_LABEL                1064
#define IDC_TERMRUSSCHARSET             1065
#define IDC_TERMRUSSHOSTLABEL           1066
#define IDC_TERMRUSSCLIENTLABEL         1067
#define IDC_WINLISTLABEL                1068
#define IDC_TCPIPTELNETKEEPALIVELABEL   1069
#define IDC_SELECT_DIR                  1070
#define IDC_BUILDTIME                   1071
#define IDC_BUILDTOOL                   1072
#define IDC_SAMPLE                      1073
#define IDC_FONTLABEL                   1088
#define IDC_SIZELABEL                   1090
#define IDC_GENHELP                     1099
#define IDD_TERMDLG                     1100
#define IDC_FONT                        1136
#define IDC_FONTSIZE                    1138
#define IDD_WINLISTDLG                  1200
#define IDC_WINLISTLIST                 1201
#define IDC_WINLISTCLOSE                1202
#define IDC_WINLISTHELP                 1299
#define IDD_TERMDLGR                    1300
#define IDD_TERMDLGK                    1301
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        103
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1074
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
