//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ttxssh.rc
//
#define IDC_ADD                         3
#define IDC_REMOVE                      4
#define IDC_EDIT                        5
#define IDI_SECURETT                    100
#define IDD_ABOUTDIALOG                 101
#define IDD_SSHSETUP                    102
#define IDD_SSHUNKNOWNHOST              103
#define IDD_SSHKEYGEN                   104
#define IDD_SSHSCP                      105
#define IDD_SSHAUTH                     106
#define IDD_SSHSCP_PROGRESS             107
#define IDD_HOSTDLG                     600
#define IDC_HOSTTCPIP                   601
#define IDD_SSHDIFFERENTHOST            601
#define IDC_HOSTSERIAL                  602
#define IDD_SSHAUTHSETUP                602
#define IDD_SSHFWDSETUP                 603
#define IDD_SSHFWDEDIT                  604
#define IDD_SSHTISAUTH                  605
#define IDC_HOSTCOMLABEL                608
#define IDC_HOSTCOM                     609
#define IDC_HOSTHELP                    699
#define IDC_HOSTNAMELABEL               997
#define IDC_HOSTNAME                    998
#define IDC_SERVICELABEL                999
#define IDC_SSHUSERNAME                 1000
#define IDC_HOSTTELNET                  1000
#define IDC_HOSTSSH                     1001
#define IDC_SSHPASSWORD                 1002
#define IDC_HOSTOTHER                   1002
#define IDC_SSHAUTHBANNER               1003
#define IDC_HOSTTCPPORTLABEL            1003
#define IDC_SSHAUTHBANNER2              1004
#define IDC_HOSTTCPPORT                 1004
#define IDC_ABOUTTEXT                   1010
#define IDC_SSHUSERNAMELABEL            1018
#define IDC_READWRITEFILENAME           1022
#define IDC_SSHCOMPRESSIONLEVEL         1023
#define IDC_SSHCIPHERPREFS              1024
#define IDC_SSHMOVECIPHERUP             1025
#define IDC_SSHMOVECIPHERDOWN           1026
#define IDC_ADDTOKNOWNHOSTS             1026
#define IDC_CONTINUE                    1027
#define IDC_READONLYFILENAME            1027
#define IDC_HOSTWARNING                 1028
#define IDC_CHOOSEREADWRITEFILE         1030
#define IDC_CHOOSEREADONLYFILE          1031
#define IDC_CHOOSERSAFILE               1031
#define IDC_RSAFILENAME                 1032
#define IDC_SSHFWDLIST                  1036
#define IDC_SSHFWDX11                   1037
#define IDC_SSHLTRFROMPORT              1038
#define IDC_SSHLTRTOHOST                1039
#define IDC_SSHLTRTOPORT                1040
#define IDC_SSHRTLFROMPORT              1041
#define IDC_SSHRTLTOHOST                1042
#define IDC_SSHRTLTOPORT                1043
#define IDC_SSHFWDLOCALTOREMOTE         1044
#define IDC_SSHPASSWORDCAPTION          1045
#define IDC_HOSTTCPPROTOCOLLABEL        1046
#define IDC_HOSTTCPPROTOCOL             1047
#define IDC_COMBO1                      1049
#define IDC_SSH_VERSION                 1049
#define IDC_SSH_VERSION_LABEL           1050
#define IDC_OPENSSL_VERSION             1051
#define IDC_HEARTBEATLABEL              1052
#define IDC_HEARTBEAT_EDIT              1053
#define IDC_HEARTBEATLABEL2             1054
#define IDC_CHECK1                      1055
#define IDC_HISTORY                     1055
#define IDC_REMEMBER_PASSWORD           1055
#define IDC_CHECKAUTH                   1055
#define IDC_CHECKIDENTITY               1055
#define IDC_FORWARDAGENT                1055
#define IDC_TTSSH_VERSION               1056
#define IDC_FORWARD_AGENT               1056
#define IDC_RSA1_TYPE                   1057
#define IDC_RSA_TYPE                    1058
#define IDC_DSA_TYPE                    1059
#define IDC_KEYTYPE                     1060
#define IDC_KEY_LABEL                   1061
#define IDC_CONFIRM_LABEL               1062
#define IDC_KEY_EDIT                    1063
#define IDC_CONFIRM_EDIT                1064
#define IDC_SAVE_PUBLIC_KEY             1065
#define IDC_SAVE_PRIBATE_KEY            1066
#define IDC_SAVE_PRIVATE_KEY            1066
#define IDC_ZLIB_VERSION                1067
#define IDC_HISTORY_LABEL               1068
#define IDC_EDIT1                       1069
#define IDC_FINGER_PRINT                1069
#define IDC_SENDFILE_EDIT               1069
#define IDC_STATIC1                     1070
#define IDC_COMPRESSLABEL               1070
#define IDC_SSHVERSIONS                 1070
#define IDC_STATIC2                     1071
#define IDC_COMPRESSNONE                1071
#define IDC_STATIC3                     1072
#define IDC_COMPLESSHIGH                1072
#define IDC_COMPRESSHIGH                1072
#define IDC_STATIC4                     1073
#define IDC_CIPHERORDER                 1073
#define IDC_STATIC5                     1074
#define IDC_KNOWNHOSTS                  1074
#define IDC_STATIC6                     1075
#define IDC_NOTICEBANNER                1075
#define IDC_HOSTWARNING2                1076
#define IDC_HOSTFINGERPRINT             1077
#define IDC_PORTFORWARD                 1078
#define IDC_XFORWARD                    1079
#define IDC_SSHFWDLOCALTOREMOTE_HOST    1080
#define IDC_SSHFWDLOCALTOREMOTE_PORT    1081
#define IDC_SSHFWDREMOTETOLOCAL_HOST    1082
#define IDC_SSHFWDREMOTETOLOCAL_PORT    1083
#define IDD_SSHFWD_BANNER               1084
#define IDD_SSHFWDBANNER                1084
#define IDC_WEBSITES                    1085
#define IDC_INCLUDES                    1086
#define IDC_CRYPTOGRAPHY                1087
#define IDC_CREDIT                      1088
#define IDC_SSHFWDLOCALTOREMOTE_CHECKIDENTITY 1089
#define IDC_SENDFILE_SELECT             1090
#define IDC_FILE_PROGRESS               1092
#define IDC_FILENAME                    1093
#define IDC_PROGRESS                    1094
#define IDC_FN_STATIC                   1095
#define IDC_RECVFILE                    1096
#define IDC_RECV                        1097
#define IDC_BUTTON1                     1098
#define IDC_SFTP_TEST                   1098
#define IDC_DUMMY_LINE                  1099
#define IDC_LOCALUSERNAMELABEL          1100
#define IDC_RECV_TO_DIRECTORY           1100
#define IDC_LOCALUSERNAME               1101
#define IDC_CHOOSEHOSTRSAFILE           1102
#define IDC_HOSTRSAFILENAME             1103
#define IDC_EDIT3                       1103
#define IDC_FP_RANDOMART                1103
#define IDC_TTSSH_ICON                  1104
#define IDC_KEYBITS_LABEL               1105
#define IDC_KEYBITS                     1106
#define IDC_KEYGEN_PROGRESS_LABEL       1107
#define IDC_SSHUSEPASSWORD              1201
#define IDC_SSHUSERSA                   1202
#define IDC_SSHFWDREMOTETOLOCAL         1202
#define IDC_SSHUSERHOSTS                1203
#define IDC_SSHUSETIS                   1204
#define IDC_SSHUSEPAGEANT               1205
#define IDC_SSHUSETIS2                  1206

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        108
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1105
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
