//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ttxssh.rc
//
#define IDC_ADD                         3
#define IDC_REMOVE                      4
#define IDC_EDIT                        5
#define IDI_SECURETT                    100
#define IDD_ABOUTDIALOG                 101
#define IDD_SSHSETUP                    102
#define IDD_SSHUNKNOWNHOST              103
#define IDD_SSHKEYGEN                   104
#define IDD_SSHSCP                      105
#define IDD_SSHAUTH                     106
#define IDD_SSHSCP_PROGRESS             107
#define IDD_SSHPASSWD_INPUT             108
#define IDD_SFTP_DIALOG                 109
#define IDI_SECURETT_YELLOW             110
#define IDD_SSHUPDATE_HOSTKEY           111
#define IDI_SECURETT_GREEN              113
#define IDD_HOSTDLG                     600
#define IDC_HOSTTCPIP                   601
#define IDD_SSHDIFFERENTKEY             601
#define IDC_HOSTSERIAL                  602
#define IDD_SSHAUTHSETUP                602
#define IDD_SSHFWDSETUP                 603
#define IDD_SSHFWDEDIT                  604
#define IDD_SSHTISAUTH                  605
#define IDD_SSHDIFFERENTTYPEKEY         606
#define IDC_HOSTCOMLABEL                608
#define IDC_HOSTCOM                     609
#define IDC_HOSTHELP                    699
#define IDC_HOSTNAMELABEL               997
#define IDC_HOSTNAME                    998
#define IDC_SERVICELABEL                999
#define IDC_SSHUSERNAME                 1000
#define IDC_HOSTTELNET                  1000
#define IDC_HOSTSSH                     1001
#define IDC_SSHPASSWORD                 1002
#define IDC_HOSTOTHER                   1002
#define IDC_SSHAUTHBANNER               1003
#define IDC_HOSTTCPPORTLABEL            1003
#define IDC_SSHAUTHBANNER2              1004
#define IDC_HOSTTCPPORT                 1004
#define IDC_ABOUTTEXT                   1010
#define IDC_SSHUSERNAMELABEL            1018
#define IDC_READWRITEFILENAME           1022
#define IDC_SSHCOMPRESSIONLEVEL         1023
#define IDC_SSHCIPHERPREFS              1024
#define IDC_SSHMOVECIPHERUP             1025
#define IDC_SSHMOVECIPHERDOWN           1026
#define IDC_ADDTOKNOWNHOSTS             1026
#define IDC_CONTINUE                    1027
#define IDC_READONLYFILENAME            1027
#define IDC_HOSTWARNING                 1028
#define IDC_SSHKEX_LIST                 1029
#define IDC_CHOOSEREADWRITEFILE         1030
#define IDC_CHOOSEREADONLYFILE          1031
#define IDC_CHOOSERSAFILE               1031
#define IDC_RSAFILENAME                 1032
#define IDC_SSHKEX_MOVEUP               1032
#define IDC_SSHKEX_MOVEDOWN             1033
#define IDC_SSHHOST_KEY_LIST            1034
#define IDC_SSHHOST_KEY_MOVEUP          1035
#define IDC_SSHFWDLIST                  1036
#define IDC_SSHHOST_KEY_MOVEDOWN        1036
#define IDC_SSHFWDX11                   1037
#define IDC_SSHMAC_LIST                 1037
#define IDC_SSHLTRFROMPORT              1038
#define IDC_SSHMAC_MOVEUP               1038
#define IDC_SSHLTRTOHOST                1039
#define IDC_SSHMAC_MOVEDOWN             1039
#define IDC_SSHLTRTOPORT                1040
#define IDC_SSHCOMP_LIST                1040
#define IDC_SSHRTLFROMPORT              1041
#define IDC_SSHCOMP_MOVEUP              1041
#define IDC_SSHRTLTOHOST                1042
#define IDC_COMP_MOVEDOWN               1042
#define IDC_SSHCOMP_MOVEDOWN            1042
#define IDC_SSHRTLTOPORT                1043
#define IDC_SSHFWDLOCALTOREMOTE         1044
#define IDC_SSHPASSWORDCAPTION          1045
#define IDC_SSHLTRLISTENADDR            1045
#define IDC_HOSTTCPPROTOCOLLABEL        1046
#define IDC_SSHRTLLISTENADDR            1046
#define IDC_HOSTTCPPROTOCOL             1047
#define IDC_COMBO1                      1049
#define IDC_SSH_VERSION                 1049
#define IDC_HOSTKEY_ROTATION_COMBO      1049
#define IDC_SSH_VERSION_LABEL           1050
#define IDC_OPENSSL_VERSION             1051
#define IDC_HEARTBEATLABEL              1052
#define IDC_HEARTBEAT_EDIT              1053
#define IDC_HEARTBEATLABEL2             1054
#define IDC_CHECK1                      1055
#define IDC_HISTORY                     1055
#define IDC_REMEMBER_PASSWORD           1055
#define IDC_CHECKAUTH                   1055
#define IDC_CHECKIDENTITY               1055
#define IDC_FORWARDAGENT                1055
#define IDC_BCRYPT_KDF_CHECK            1055
#define IDC_TTSSH_VERSION               1056
#define IDC_FORWARD_AGENT               1056
#define IDC_FORWARDAGENTCONFIRM         1056
#define IDC_RSA1_TYPE                   1057
#define IDC_RSA_TYPE                    1058
#define IDC_DSA_TYPE                    1059
#define IDC_KEYTYPE                     1060
#define IDC_KEY_LABEL                   1061
#define IDC_CONFIRM_LABEL               1062
#define IDC_KEY_EDIT                    1063
#define IDC_CONFIRM_EDIT                1064
#define IDC_SAVE_PUBLIC_KEY             1065
#define IDC_SAVE_PRIBATE_KEY            1066
#define IDC_SAVE_PRIVATE_KEY            1066
#define IDC_ZLIB_VERSION                1067
#define IDC_ECDSA256_TYPE               1067
#define IDC_HISTORY_LABEL               1068
#define IDC_ECDSA384_TYPE               1068
#define IDC_FINGER_PRINT                1069
#define IDC_SENDFILE_EDIT               1069
#define IDC_PASSWD                      1069
#define IDC_ECDSA521_TYPE               1069
#define IDC_SFTP_EDIT                   1069
#define IDC_ADDKEY_EDIT                 1069
#define IDC_STATIC1                     1070
#define IDC_COMPRESSLABEL               1070
#define IDC_SSHVERSIONS                 1070
#define IDC_STATIC2                     1071
#define IDC_COMPRESSNONE                1071
#define IDC_STATIC3                     1072
#define IDC_COMPLESSHIGH                1072
#define IDC_COMPRESSHIGH                1072
#define IDC_STATIC4                     1073
#define IDC_CIPHERORDER                 1073
#define IDC_STATIC5                     1074
#define IDC_KNOWNHOSTS                  1074
#define IDC_STATIC6                     1075
#define IDC_NOTICEBANNER                1075
#define IDC_HOSTWARNING2                1076
#define IDC_KEX_ORDER                   1076
#define IDC_HOSTFINGERPRINT             1077
#define IDC_HOST_KEY_ORDER              1077
#define IDC_PORTFORWARD                 1078
#define IDC_MAC_ORDER                   1078
#define IDC_XFORWARD                    1079
#define IDC_COMP_ORDER                  1079
#define IDC_SSHFWDLOCALTOREMOTE_HOST    1080
#define IDC_COMPRESSNOTE                1080
#define IDC_SSHFWDLOCALTOREMOTE_PORT    1081
#define IDC_SSHFWDREMOTETOLOCAL_HOST    1082
#define IDC_SSHFWDREMOTETOLOCAL_PORT    1083
#define IDD_SSHFWD_BANNER               1084
#define IDD_SSHFWDBANNER                1084
#define IDC_WEBSITES                    1085
#define IDC_SSHFWDLOCALTOREMOTE_LISTEN  1085
#define IDC_INCLUDES                    1086
#define IDC_SSHFWDREMOTETOLOCAL_LISTEN  1086
#define IDC_CRYPTOGRAPHY                1087
#define IDC_CREDIT                      1088
#define IDC_SSHFWDLOCALTOREMOTE_CHECKIDENTITY 1089
#define IDC_SENDFILE_SELECT             1090
#define IDC_FILE_PROGRESS               1092
#define IDC_FILENAME                    1093
#define IDC_RECVDIR_SELECT              1093
#define IDC_PROGRESS                    1094
#define IDC_FN_STATIC                   1095
#define IDC_RECVFILE                    1096
#define IDC_RECV                        1097
#define IDC_BUTTON1                     1098
#define IDC_SFTP_TEST                   1098
#define IDC_DUMMY_LINE                  1099
#define IDC_LOCALUSERNAMELABEL          1100
#define IDC_RECV_TO_DIRECTORY           1100
#define IDC_LOCALUSERNAME               1101
#define IDC_RECVFILE_TO                 1101
#define IDC_CHOOSEHOSTRSAFILE           1102
#define IDC_HOSTRSAFILENAME             1103
#define IDC_FP_RANDOMART                1103
#define IDC_CONFIRM_PASSWD              1103
#define IDC_TTSSH_ICON                  1104
#define IDC_KEYBITS_LABEL               1105
#define IDC_KEYBITS                     1106
#define IDC_KEYGEN_PROGRESS_LABEL       1107
#define IDC_PROGBAR                     1108
#define IDC_BCRYPT_KDF_ROUNDS_LABEL     1108
#define IDC_PROGTIME                    1109
#define IDC_BCRYPT_KDF_ROUNDS           1109
#define IDC_HOSTSSHFPCHECK              1110
#define IDC_HOSTSSHFPDNSSEC             1111
#define IDC_VERIFYHOSTKEYDNS            1112
#define IDC_COMMENT_LABEL               1113
#define IDC_COMMENT_EDIT                1114
#define IDC_SSHUSEPASSWORD              1201
#define IDC_SSHUSERSA                   1202
#define IDC_SSHFWDREMOTETOLOCAL         1202
#define IDC_SSHUSERHOSTS                1203
#define IDC_SSHUSETIS                   1204
#define IDC_SSHUSEPAGEANT               1205
#define IDC_SSHUSETIS2                  1206
#define IDC_REMEMBERPASSWORD            1207
#define IDC_SENDFILE_TO                 1208
#define IDC_SFTP_CONSOLE                1208
#define IDC_REMOVEKEY_EDIT              1208
#define IDC_PUTTY_VERSION               1209
#define IDC_ED25519_TYPE                1211
#define IDC_HOSTKEY_ROTATION_STATIC     1212
#define IDC_LIST1                       1213
#define IDC_MESSAGE                     1214
#define IDC_HOSTKEY_MESSAGE             1214
#define IDC_ADDKEY_TEXT                 1215
#define IDC_REMOVEKEY_TEXT              1216
#define IDC_FP_HASH_ALG                 1217
#define IDC_FP_HASH_ALG_MD5             1218
#define IDC_FP_HASH_ALG_SHA256          1219
#define IDC_FORWARDAGENTNOTIFY          1220
#define IDC_OLD_PASSWD                  1221
#define IDC_OLD_PASSWD_LABEL            1222
#define IDC_NEW_PASSWD                  1223
#define IDC_NEW_PASSWD_LABEL            1224
#define IDC_CONFIRM_PASSWD_LABEL        1225
#define IDC_PASSWD_CHANGEREQ_MSG        1226
#define IDC_SSHFWDLOCALDYNAMIC          1227
#define IDC_SSHDYNFROMPORT              1228
#define IDC_SSHFWDLOCALDYNAMIC_LISTEN   1229
#define IDC_SSHDYNLISTENADDR            1230
#define IDC_SSHPASSWORD_OPTION          1231
#define IDC_USERNAME_OPTION             1232
#define IDC_HOSTRSAFILENAMELABEL        1235
#define IDC_RSAFILENAMELABEL            1236
#define IDC_SSH_NO_USERNAME             1237
#define IDC_SSH_DEFAULTUSERNAME         1238
#define IDC_SSH_WINDOWS_USERNAME        1239
#define IDC_SSH_WINDOWS_USERNAME_TEXT   1241

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        118
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1242
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
