/* This file was generated by buildtools/svnrev/svnrev.pl */
/* #define TT_VERSION_STR "5.2-dev" check teraterm/common/tt-version.h */
#define GITVERSION "48287fc54"
#undef SVNVERSION
#undef TERATERM_RELEASE
#define BRANCH_NAME "main"
