//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by t:\ttssh2\teraterm\teraterm\ttermpro.rc
//
#define IDI_TTERM                       100
#define IDR_ACC                         100
#define IDR_MENU                        100
#define IDI_VT                          101
#define IDI_TEK                         102
#define IDI_TTERM_CLASSIC               103
#define IDI_VT_CLASSIC                  104
#define IDI_CYGTERM                     105
#define IDD_COMMENT_DIALOG              110
#define IDD_EXTERNAL_SETUP              111
#define IDD_TABSHEET_GENERAL            111
#define IDD_BROADCAST_DIALOG            112
#define IDD_TABSHEET_VISUAL             116
#define IDD_TABSHEET_LOG                117
#define IDD_TABSHEET_CYGWIN             118
#define IDR_MENU1                       119
#define IDR_PASTEMENU                   119
#define IDD_CLIPBOARD_DIALOG            120
#define IDR_TEKMENU                     1000
#define IDC_EDIT_COMMENT                1000
#define IDC_EDIT_FULLPATH               1001
#define IDC_FULLPATH_LABEL              1002
#define IDC_LINECOPY                    1003
#define IDC_MOUSE_CURSOR                1004
#define IDC_ALPHA_BLEND                 1008
#define IDC_CYGWIN_PATH                 1009
#define IDC_SELECT_FILE                 1010
#define IDC_DELIM_LIST                  1011
#define IDC_ANSI_COLOR                  1012
#define IDC_COLOR_RED                   1013
#define IDC_COLOR_GREEN                 1014
#define IDC_COLOR_BLUE                  1015
#define IDC_SAMPLE_COLOR                1016
#define IDC_COMMAND_EDIT                1017
#define IDC_ENTERKEY_CHECK              1018
#define IDC_RADIO_CRLF                  1019
#define IDC_RADIO_CR                    1020
#define IDC_RADIO_LF                    1021
#define IDC_ENTERGROUP                  1022
#define IDC_VIEWLOG_LABEL               1023
#define IDC_VIEWLOG_EDITOR              1024
#define IDC_VIEWLOG_PATH                1025
#define IDC_DEFAULTNAME_LABEL           1026
#define IDC_DEFAULTNAME_EDITOR          1027
#define IDC_ETERM_LOOKFEEL              1030
#define IDC_DISABLE_PASTE_RBUTTON       1032
#define IDC_CLICKABLE_URL               1033
#define IDC_CONFIRM_PASTE_RBUTTON       1034
#define IDC_TERM_TYPE                   1035
#define IDC_DISABLE_SENDBREAK           1035
#define IDC_PORT_START                  1036
#define IDC_SELECT_LBUTTON              1036
#define IDC_PORT_RANGE                  1037
#define IDC_SHELL                       1038
#define IDC_TERM_EDIT                   1039
#define IDC_ENV1                        1040
#define IDC_EDIT7                       1041
#define IDC_ENV2                        1041
#define IDC_MOUSE                       1042
#define IDC_DELIMITER                   1043
#define IDC_ANSICOLOR                   1044
#define IDC_RED                         1045
#define IDC_GREEN                       1046
#define IDC_BLUE                        1047
#define IDC_ALPHABLEND                  1048
#define IDC_CYGWIN_PATH_LABEL           1049
#define IDC_CYGWIN                      1050
#define IDC_TERM_LABEL                  1051
#define IDC_TERMTYPE_LABEL              1052
#define IDC_PORTSTART_LABEL             1053
#define IDC_PORTRANGE_LABEL             1054
#define IDC_SHELL_LABEL                 1055
#define IDC_ENV2_LABEL                  1056
#define IDC_ENV1_LABEL                  1057
#define IDC_HISTORY_CHECK               1058
#define IDC_ACCEPT_BROADCAST            1059
#define IDC_LOGIN_SHELL                 1059
#define IDC_PARENT_ONLY                 1060
#define IDC_HOME_CHDIR                  1060
#define IDC_DEFAULTPATH_PUSH            1061
#define IDC_DEFAULTPATH_EDITOR          1062
#define IDC_DEFAULTPATH_LABEL           1063
#define IDC_AUTOSCROLL_ONLY_IN_BOTTOM_LINE 1064
#define IDC_ACCEPT_MOUSE_EVENT_TRACKING 1065
#define IDC_ACCEPT_TITLE_CHANGING       1066
#define IDC_AGENT_PROXY                 1067
#define IDC_DISABLE_MOUSE_TRACKING_CTRL 1068
#define IDC_ENABLE_ATTR_COLOR_BOLD      1069
#define IDC_ENABLE_ATTR_COLOR_BLINK     1070
#define IDC_ENABLE_ATTR_COLOR_REVERSE   1071
#define IDC_ENABLE_URL_COLOR            1072
#define IDC_ENABLE_ANSI_COLOR           1073
#define IDC_DISABLE_PASTE_MBUTTON       1074
#define IDD_PRNABORTDLG                 2100
#define IDD_FILETRANSDLG                2200
#define IDC_TRANSFNAME                  2201
#define IDC_TRANSBYTES                  2202
#define IDC_TRANSPAUSESTART             2203
#define IDC_TRANSCLOSE                  2204
#define IDC_TRANSHELP                   2299
#define IDD_PROTDLG                     2300
#define IDC_PROTOFNAME                  2301
#define IDD_TABSHEET_COPYPASTE          2301
#define IDC_PROTOPROT                   2302
#define IDC_PROTOPKTNUM                 2303
#define IDC_PROTOBYTECOUNT              2304
#define IDC_PROTOPERCENT                2305
#define IDC_PRNABORT_PRINTING           2400
#define IDC_PROT_FILENAME               2501
#define IDC_PROT_PROT                   2502
#define IDC_PROT_PACKET                 2503
#define IDC_PROT_TRANS                  2504
#define IDC_TRANS_FILENAME              2505
#define IDC_TRANS_TRANS                 2506
#define IDC_AUTOSTART                   2507
#define IDC_REALTIME_CHECK              2508
#define IDC_LIST1                       2509
#define IDC_LIST                        2509
#define IDC_EDIT1                       2510
#define IDC_EDIT                        2510
#define IDC_SCROLL_LINE                 2510
#define IDC_PASTEDELAY_EDIT             2510
#define IDC_CLIPBOARD_INFO              2511
#define IDC_CHECK1                      2512
#define IDC_CONFIRM_CHANGE_PASTE        2512
#define IDC_MOUSEWHEEL_SCROLL_LINE      2513
#define IDC_TRANSPROGRESS               2514
#define IDC_PROTOPROGRESS               2515
#define IDC_ACCEPT_TITLE_CHANGING_LABEL 2517
#define IDC_PASTEDELAY_LABEL            2518
#define IDC_PASTEDELAY_LABEL2           2519
#define IDC_CONFIRM_STRING_FILE         2520
#define IDC_CONFIRM_STRING_FILE_PATH    2521
#define IDC_CONFIRM_STRING_FILE_LABEL   2522
#define ID_ACC_SENDBREAK                50001
#define ID_ACC_COPY                     50002
#define ID_ACC_NEWCONNECTION            50003
#define ID_ACC_PRINT                    50004
#define ID_ACC_EXIT                     50005
#define ID_ACC_PASTECR                  50006
#define ID_ACC_AREYOUTHERE              50007
#define ID_ACC_PASTE                    50008
#define ID_ACC_DISCONNECT               50009
#define ID_FILE_NEWCONNECTION           50110
#define ID_FILE_DUPLICATESESSION        50111
#define ID_FILE_CYGWINCONNECTION        50112
#define ID_FILE_LOG                     50120
#define ID_FILE_COMMENTTOLOG            50121
#define ID_FILE_VIEWLOG                 50122
#define ID_FILE_SHOWLOGDIALOG           50123
#define ID_FILE_SENDFILE                50130
#define ID_FILE_KERMITRCV               50141
#define ID_FILE_KERMITGET               50142
#define ID_FILE_KERMITSEND              50143
#define ID_FILE_KERMITFINISH            50144
#define ID_FILE_XRCV                    50145
#define ID_FILE_XSEND                   50146
#define ID_FILE_ZRCV                    50151
#define ID_FILE_ZSEND                   50152
#define ID_FILE_BPRCV                   50153
#define ID_FILE_BPSEND                  50154
#define ID_FILE_QVRCV                   50155
#define ID_FILE_QVSEND                  50156
#define ID_FILE_YRCV                    50157
#define ID_FILE_YSEND                   50158
#define ID_FILE_CHANGEDIR               50170
#define ID_FILE_REPLAYLOG               50171
#define ID_FILE_LOGMEIN                 50172
#define ID_FILE_PRINT2                  50180
#define ID_FILE_DISCONNECT              50190
#define ID_FILE_EXIT                    50199
#define ID_EDIT_COPY2                   50210
#define ID_EDIT_COPYTABLE               50220
#define ID_EDIT_PASTE2                  50230
#define ID_EDIT_PASTECR                 50240
#define ID_EDIT_CLEARSCREEN             50250
#define ID_EDIT_CLEARBUFFER             50260
#define ID_EDIT_CANCELSELECT            50270
#define ID_EDIT_SELECTSCREEN            50280
#define ID_EDIT_SELECTALL               50290
#define ID_SETUP_TERMINAL               50310
#define ID_SETUP_WINDOW                 50320
#define ID_SETUP_FONT                   50330
#define ID_SETUP_KEYBOARD               50340
#define ID_SETUP_SERIALPORT             50350
#define ID_SETUP_TCPIP                  50360
#define ID_SETUP_GENERAL                50370
#define ID_SETUP_ADDITIONALSETTINGS     50375
#define ID_SETUP_SAVE                   50380
#define ID_SETUP_RESTORE                50390
#define ID_SETUP_LOADKEYMAP             50395
#define ID_CONTROL_RESETTERMINAL        50410
#define ID_CONTROL_RESETREMOTETITLE     50411
#define ID_CONTROL_AREYOUTHERE          50420
#define ID_CONTROL_SENDBREAK            50430
#define ID_CONTROL_RESETPORT            50440
#define ID_CONTROL_BROADCASTCOMMAND     50445
#define ID_CONTROL_OPENTEK              50450
#define ID_CONTROL_CLOSETEK             50460
#define ID_CONTROL_MACRO                50470
#define ID_HELP_INDEX2                  50910
#define ID_HELP_USING2                  50920
#define ID_HELP_ABOUT                   50990
#define ID_TEKFILE_PRINT                51110
#define ID_TEKFILE_EXIT                 51190
#define ID_TEKEDIT_COPY                 51210
#define ID_TEKEDIT_COPYSCREEN           51220
#define ID_TEKEDIT_PASTE                51230
#define ID_TEKEDIT_PASTECR              51240
#define ID_TEKEDIT_CLEARSCREEN          51250
#define ID_TEKSETUP_WINDOW              51310
#define ID_TEKSETUP_FONT                51320
#define ID_TEKVTWIN                     51410
#define ID_TEKHELP_INDEX                51910
#define ID_TEKHELP_USING                51920
#define ID_TEKHELP_ABOUT                51990
#define ID_EDIT_EXTERNALSETUP           52005
#define ID_FILE_TERATERMMENU            52006

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        121
#define _APS_NEXT_COMMAND_VALUE         52030
#define _APS_NEXT_CONTROL_VALUE         2523
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
