perl ..\installer\2sjis.pl --i ..\libs\oniguruma\COPYING --o en\html\reference\Oniguruma-LICENSE.txt --c euc-jp --l unix
perl ..\installer\2sjis.pl --i ..\libs\oniguruma\COPYING --o ja\html\reference\Oniguruma-LICENSE.txt --c euc-jp --l unix
perl ..\installer\2sjis.pl --i ..\libs\oniguruma\doc\RE    --o en\html\reference\RE.txt --c euc-jp --l unix
perl ..\installer\2sjis.pl --i ..\libs\oniguruma\doc\RE.ja --o ja\html\reference\RE.txt --c euc-jp --l unix
perl ..\installer\2sjis.pl --i ..\libs\openssl\LICENSE  --o en\html\reference\OpenSSL-LICENSE.txt --c euc-jp --l unix
perl ..\installer\2sjis.pl --i ..\libs\openssl\LICENSE  --o ja\html\reference\OpenSSL-LICENSE.txt --c euc-jp --l unix
perl ..\installer\2sjis.pl --i ..\libs\putty\LICENCE  --o en\html\reference\PuTTY-LICENSE.txt --c shiftjis --l crlf
perl ..\installer\2sjis.pl --i ..\libs\putty\LICENCE  --o ja\html\reference\PuTTY-LICENSE.txt --c shiftjis --l crlf
perl ..\installer\2sjis.pl --i ..\libs\SFMT\LICENSE.txt --o en\html\reference\SFMT-LICENSE.txt --c shiftjis --l unix
perl ..\installer\2sjis.pl --i ..\libs\SFMT\LICENSE.txt --o ja\html\reference\SFMT-LICENSE.txt --c shiftjis --l unix
perl ..\installer\2sjis.pl --i ..\cygterm\COPYING  --o en\html\reference\CygTerm+-LICENSE.txt --c shiftjis --l unix
perl ..\installer\2sjis.pl --i ..\cygterm\COPYING  --o ja\html\reference\CygTerm+-LICENSE.txt --c shiftjis --l unix
