#!/usr/bin/perl
use strict;
use utf8;

my $fname_in = "shiftjis.txt";
my $fname_out = "shiftjis.ini";
if (@ARGV == 2) {
	$fname_in = $ARGV[0];
	$fname_out = $ARGV[1];
} else {
	my $n = @ARGV;
	printf "argv $n\n";
	exit 1;
}

my @unicode_array = ();

open(FILE_IN, $fname_in) || die "Cannot open $fname_in.";
open(FILE_OUT, ">:crlf:utf8", $fname_out) || die "Cannot open $fname_out.";
print FILE_OUT "\x{feff}";	# BOM
print FILE_OUT "// this file was generated by shiftjis.pl\n";

while(my $a = <FILE_IN>) {
	if ($a =~ /^0x([0-9A-Fa-f]+)\s+0x([0-9A-Fa-f]+)\s+#\s*(.+)$/) {
		my $sjis = hex $1;
		my $unicode = hex $2;
		my $name = $3;
		print "$sjis $name\n";
		if ($unicode >= 0x80) {
			push @unicode_array, $unicode;
		}
	}
}
close(FILE_IN);

my @sorted_unicode = sort { $a <=> $b } @unicode_array;

# 出力
my $index = 1;
my $start = 0;
my $end = 0;
foreach my $u (@sorted_unicode) {
	if ($start == 0) {
		$start = $u;
		$end = $u;
	} elsif ($u == $end + 1) {
		$end = $u;
	} else {
		if ($start == $end) {
			printf FILE_OUT ("Range%d=U+%06x, 2\n", $index, $start);
		} else {
			printf FILE_OUT ("Range%d=U+%06x, U+%06x, 2\n", $index, $start, $end);
		}
		$start = 0;
		$end = 0;
		$index += 1;
	}
}
if ($start != 0) {
	if ($start == $end) {
		printf FILE_OUT ("Range%d=U+%06x, 2\n", $index, $start);
	} else {
		printf FILE_OUT ("Range%d=U+%06x, U+%06x, 2\n", $index, $start, $end);
	}
}
