
include(${CMAKE_CURRENT_LIST_DIR}/script_support.cmake)

if(APPLE)
  # On macOS, SFMT is built as a subproject or found via Homebrew
  # First check if prebuilt exists, otherwise use system/Homebrew
  set(SFMT_ROOT "${CMAKE_CURRENT_LIST_DIR}/SFMT_${TOOLSET}")
  if(EXISTS "${SFMT_ROOT}/include")
    set(SFMT_INCLUDE_DIRS "${SFMT_ROOT}/include")
    set(SFMT_LIBRARY_DIRS "${SFMT_ROOT}/lib")
    set(SFMT_LIB ${SFMT_LIBRARY_DIRS}/libsfmt.a)
  else()
    # Build SFMT from bundled source if available
    set(SFMT_SRC_DIR "${CMAKE_CURRENT_LIST_DIR}/../libs_src/SFMT")
    if(EXISTS "${SFMT_SRC_DIR}/SFMT.c")
      add_library(sfmt_builtin STATIC ${SFMT_SRC_DIR}/SFMT.c)
      target_include_directories(sfmt_builtin PUBLIC ${SFMT_SRC_DIR})
      target_compile_definitions(sfmt_builtin PRIVATE -DMEXP=19937)
      set(SFMT_INCLUDE_DIRS "${SFMT_SRC_DIR}")
      set(SFMT_LIB sfmt_builtin)
    else()
      # Fallback: empty (SFMT is optional PRNG)
      message(WARNING "SFMT not found - building without SFMT support")
      set(SFMT_INCLUDE_DIRS "")
      set(SFMT_LIB "")
    endif()
  endif()
elseif(MSVC)
  set(SFMT_ROOT "${CMAKE_CURRENT_LIST_DIR}/SFMT_vs_${CMAKE_VS_PLATFORM_TOOLSET}_${CMAKE_GENERATOR_PLATFORM}")
  set(SFMT_INCLUDE_DIRS "${SFMT_ROOT}/include")
  set(SFMT_LIBRARY_DIRS "${SFMT_ROOT}/lib")
  if(IS_MULTI_CONFIG)
    set(SFMT_LIB
      optimized ${SFMT_LIBRARY_DIRS}/sfmt.lib
      debug ${SFMT_LIBRARY_DIRS}/sfmtd.lib
    )
  else()
    set(SFMT_LIB ${SFMT_LIBRARY_DIRS}/sfmt.lib)
  endif()
else()
  set(SFMT_ROOT ${CMAKE_CURRENT_LIST_DIR}/SFMT_${TOOLSET})
  set(SFMT_INCLUDE_DIRS "${SFMT_ROOT}/include")
  set(SFMT_LIBRARY_DIRS "${SFMT_ROOT}/lib")
  set(SFMT_LIB ${SFMT_LIBRARY_DIRS}/libsfmt.a)
endif()
