
string(REPLACE " " "_" GENERATOR_ ${CMAKE_GENERATOR})

set(SFMT_INCLUDE_DIRS
  "${CMAKE_CURRENT_LIST_DIR}/SFMT_${GENERATOR_}/include"
  )

set(SFMT_LIBRARY_DIRS
  "${CMAKE_CURRENT_LIST_DIR}/SFMT_${GENERATOR_}/lib"
  )
