# TOOLSET ツールセット名
if(${CMAKE_GENERATOR} MATCHES "Visual Studio")
  if(${CMAKE_GENERATOR} MATCHES "Visual Studio 18 2026")
    set(MSVC_TOOLSET_VERSION 145)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 17 2022")
    set(MSVC_TOOLSET_VERSION 143)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 16 2019")
    set(MSVC_TOOLSET_VERSION 142)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 15 2017")
    # ARM64 available (Win32,x64,ARM,ARM64)
    set(MSVC_TOOLSET_VERSION 141)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 14 2015")
    set(MSVC_TOOLSET_VERSION 140)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 12 2013")
    # ARCHITECTURE is available 2013+ (Win32,x64,ARM)
    set(MSVC_TOOLSET_VERSION 120)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 11 2012")
    set(MSVC_TOOLSET_VERSION 110)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 10 2010")
    set(MSVC_TOOLSET_VERSION 100)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 9 2008")
    set(MSVC_TOOLSET_VERSION 90)
  elseif(${CMAKE_GENERATOR} MATCHES "Visual Studio 8 2005")
    set(MSVC_TOOLSET_VERSION 80)
  else()
    set(MSVC_TOOLSET_VERSION "Unknown")
    message(FATAL_ERROR "unknown Visual Studio ${CMAKE_GENERATOR}")
  endif()
  set(TOOLSET "vs_v${MSVC_TOOLSET_VERSION}_${ARCHITECTURE}")
elseif((${CMAKE_GENERATOR} MATCHES "Unix Makefiles") OR
    (${CMAKE_GENERATOR} MATCHES "MSYS Makefiles") OR
    (${CMAKE_GENERATOR} MATCHES "MinGW Makefiles") OR
    (${CMAKE_GENERATOR} MATCHES "Ninja"))
  if(DEFINED ARCHITECTURE)
    # for script
    if(${ARCHITECTURE} STREQUAL "x86_64")
      set(TOOLSET "mingw_x86_64")
    elseif(${ARCHITECTURE} STREQUAL "i686")
      set(TOOLSET "mingw_i686")
    else()
      message(FATAL_ERROR "check ARCHITECTURE ${ARCHITECTURE}")
    endif()
  else()
    # for generate/build
    if(CMAKE_SIZEOF_VOID_P EQUAL 8)
      set(TOOLSET "mingw_x86_64")
    else()
      set(TOOLSET "mingw_i686")
    endif()
  endif()
elseif(${CMAKE_GENERATOR} MATCHES "NMake Makefiles")
  set(TOOLSET "VS_NMake")
else()
  message(FATAL_ERROR "unknown GENERATOR ${CMAKE_GENERATOR}")
endif()
