# write to CMakeCache.txt
set(CMAKE_C_FLAGS_DEBUG "/DWIN32 /D_WINDOWS /W3 /MDd /Zi /Ob0 /Od /RTC1" CACHE STRING "" FORCE)
set(CMAKE_C_FLAGS_RELEASE "/DWIN32 /D_WINDOWS /W3 /MD /O2 /Ob2 /DNDEBUG" CACHE STRING "" FORCE)
