name: Build installer

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - vs-version: '17'
            VS_VERSION: 2022
            windows: windows-2022
    runs-on: ${{ matrix.windows }}
    env:
      NOPAUSE: 1
      VS_VERSION: ${{ matrix.VS_VERSION }}

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: ${{ matrix.vs-version }}

    - name: Restore cached libs
      id: cache-libs-restore
      uses: actions/cache/restore@v4
      with:
        path: |
          libs
          buildtools
        key: cache-${{ matrix.VS_VERSION }}-${{ hashFiles('.github/workflows/msbuild.yml', 'buildtools/*.cmake', 'ci_scripts/*.cmake') }}
        restore-keys: |
            cache-${{ matrix.VS_VERSION }}-
            cache-

    - uses: msys2/setup-msys2@v2

    - name: install_cygwin
      run: |
        chcp 932
        buildtools/install_cygwin.bat

    - name: install_innosetup
      run: |
        chcp 932
        buildtools/install_innosetup.bat

    - name: build_script
      run: |
        chcp 932
        ci_scripts/build_appveyor_release_bat.bat

    - name: Upload artifacts (zip)
      uses: actions/upload-artifact@v4
      with:
        name: zip-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*.zip
          !installer/Output/*_pdb.zip

    - name: Upload artifacts (pdb)
      uses: actions/upload-artifact@v4
      with:
        name: pdb-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*_pdb.zip

    - name: Upload artifacts (exe)
      uses: actions/upload-artifact@v4
      with:
        name: installer-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*.exe

    - name: Upload artifacts (sha256sum)
      uses: actions/upload-artifact@v4
      with:
        name: sha256sum-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*.sha256sum

    - name: Upload artifacts (sha512sum)
      uses: actions/upload-artifact@v4
      with:
        name: sha512sum-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*.sha512sum

    - name: Calculate cache hash
      id: cache_hash
      shell: bash
      run: |
        HASH_OUTPUT=${{ hashFiles('.github/workflows/msbuild.yml', 'buildtools/*.cmake', 'ci_scripts/*.cmake') }}
        echo "hash_value=$HASH_OUTPUT" >> $GITHUB_OUTPUT

    - name: pre_cache
      run: |
        chcp 932
        ci_scripts/build_appveyor_release_bat_pre_cache.bat

    - name: save cache
      if: steps.cache-libs-restore.outputs.cache-hit != 'true'   # restore時keyが完全に一致したときtrue
      id: cache-libs-save
      uses: actions/cache/save@v4
      with:
        path: |
          libs
          buildtools
        key: cache-${{ matrix.VS_VERSION }}-${{ steps.cache_hash.outputs.hash_value }}

