name: Build installer

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - vs-version: '17'
            VS_VERSION: 2022
            windows: windows-2022
    runs-on: ${{ matrix.windows }}
    env:
      NOPAUSE: 1
      VS_VERSION: ${{ matrix.VS_VERSION }}

    steps:
    - uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: ${{ matrix.vs-version }}

    - name: Restore cached libs
      id: cache-libs-restore
      uses: actions/cache/restore@v4
      with:
        path: libs
        key: ${{ matrix.VS_VERSION }}-${{ github.event_name }}-${{ hashFiles('.github/workflows/msbuild.yml', 'buildtools/*.bat', 'ci_scripts/*.bat') }}

    - name: download setup-x86_64.exe
      run: |
        chcp 932
        mkdir buildtools\cygwin64
        curl https://www.cygwin.com/setup-x86_64.exe --output buildtools\cygwin64\setup-x86_64.exe

    - uses: msys2/setup-msys2@v2

    - name: before_build (install_cygwin)
      run: |
        chcp 932
        buildtools/install_cygwin.bat

    - name: before_build (install_innosetup)
      run: |
        chcp 932
        buildtools/install_innosetup.bat

    - name: build_script
      run: |
        chcp 932
        ci_scripts/build_appveyor_release_bat.bat

    - name: after_build
      run: |
        chcp 932
        ci_scripts/build_appveyor_release_bat_pre_cache.bat

    - name: Upload artifacts (zip)
      uses: actions/upload-artifact@v4
      with:
        name: binary-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*.zip

    - name: Upload artifacts (exe)
      uses: actions/upload-artifact@v4
      with:
        name: installer-BUILD-${{ github.run_number }}-${{ github.run_id }}-VS${{ matrix.VS_VERSION }}
        path: |
          installer/Output/*.exe

    - name: Save libs
      if: steps.cache-libs-restore.outputs.cache-hit != 'true'
      id: cache-libs-save
      uses: actions/cache/save@v4
      with:
        path: |
          libs
        key: ${{ matrix.VS_VERSION }}-${{ github.event_name }}-${{ hashFiles('.github/workflows/msbuild.yml', 'buildtools/*.bat', 'ci_scripts/*.bat') }}

